### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [jeswheel/arima2#1]
I suggest adding topics such as `arima`, `time-series-analysis` in the About section at https://github.com/jeswheel/arima2 .

Thanks for your project -- I have fit arima models in R.

**Comment by jeswheel** [comment]
Thanks for the suggestion. I have added a few to the project about section.

**Comment by Beliavsky** [comment]
Thanks -- another topic to add is `r-package`, which has 3.1K results.
